config/routes.rb
SampleApp::Application.routes.draw do
  resources :users

  root :to => 'pages#home'
    
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  get "pages/home"
  
 

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name,  :presence => true,
                     :length   => { :maximum => 50 }
	validates :email, :presence => true,
                     :format   => { :with => email_regex },
		     :uniqueness => { :case_sensitive => false }  # implicit ":uniqueness => true"
	validates :password, :presence => true,
				     :confirmation => true,
				     :length => { :within => 6..40 }
				     
	before_save :encrypt_password 
	
	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end
	
	def User.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil 		if user.nil?
		return user	if user.has_password?(submitted_password)
	end
		
	private
	def encrypt_password
		# self because it's in the same User Class ;)
		self.salt = make_salt if new_record?
		self.encrypted_password = encrypt(password)
	end
	def encrypt(string)
		secure_hash("#{salt}--#{string}")
	end
	
	def make_salt
		secure_hash("#{Time.now.utc}--#{password}")
	end
	
	def secure_hash(string)
		Digest::SHA2.hexdigest(string)
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	  @title = "Home"
  end

  def contact
	  @title = "Contact"
  end
  
  def about
	  @title = "About"
  end
  
  def help
	  @title = "Help"
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
	@users = User.all
  end  
  def show
	@user = User.find(params[:id])
	@title = @user.name
  end
  
  def new
	  @user = User.new
	  @title = "Sign up"
  end

  def create
	#raise params[:user].inspect
	@user = User.new(params[:user])
	if @user.save
		##### En 2 lineas:
		#flash[:success] = "Welcome to the Sample App!"
		#redirect_to user_path(@user)  # Puede ser "@user" en vez de "user_path(@user)" 
		##### En 1 linea: 
		redirect_to user_path(@user), :flash => { :success => "Welcome to the Sample App!" }
	else
		@title = "Sign up"
		render 'new'
	end
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logo
	  @logo = image_tag('logo.png', :alt => 'Sample App', :class => 'round')
  end
  
  def title
	  base_title = "Ruby on Rails Tutorial Sample App"
	if @title.nil?
		  base_title
	else
		"#{base_title} | #{@title}"
	end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end

end

app/views/layouts/_footer.html.erb
<footer>
        <nav class="round">
          <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
	  <li><%= link_to "News", '#' %></li>
            <li><%= link_to "Terms of Service", '#' %></li>
          </ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<%= link_to logo, root_path %>
<% link_to(image_tag("logo.png", :alt => "Sample App", :class => "round"), root_path) %>
<nav class="round">
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Help", help_path %></li>
    <li><%= link_to "Sign in", signup_path %></li>
  </ul>
</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
    <%= csrf_meta_tags %> 
    <%= render 'layouts/stylesheets' %>
 </head>
  <body>
    <div class="container">
	<%= render 'layouts/header' %>
      <section class="round">
	<% flash.each do |key, value| %>
	<div class="flash <%= key %>"><%= value %></div>
	<% end %>
        <%= yield %>
      </section>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Testing</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#Help</h1>
<p>Help page</p>

app/views/pages/home.html.erb
<h1>Sample App</h1>

<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(@user.errors.count, "error") %>
			prohibited this user from being saved:
		</h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% @user.errors.full_messages.each do |message| %>
		  <li><%= message %></li>
		<% end %>
		</ul>
	</div>

<% end %>

app/views/users/index.html.erb
<table class="profile" summary="Profile information">
   <tr>
	<td class="main">
		<% @users.each do |user| %>
			<h1>
				<%= gravatar_for user %>
				<%= user.name %>
			</h1>
		<% end %>
	</td>
	<td class="sidebar round">
	</td>
   </tr>
</table>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>	
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
   <tr>
	<td class="main">
		<h1>

		<%= gravatar_for @user %>
		<%= @user.name %>
		</h1>
	</td>
	<td class="sidebar round">
		<strong>Name</strong> <%= @user.name %> <br />
		<strong>URL</strong>   <%= link_to user_path(@user), user_path(@user) %>
	</td>
   </tr>
</table>